### ISSUE TITLE
speech act classifier?

### ISSUE THREAD

**Issue by glicerico** [guillaume-chevalier/SGNN-Self-Governing-Neural-Networks-Projection-Layer#3]
Thanks for your work Guillaume.
Did you implement the speech act classifier as in the SGNN paper? If you did, I wonder what scores did you get, as I am trying to do it myself and I am inspired by your implementation.

**Comment by guillaume-chevalier** [comment]
I didn't implement any classifier. The code here stands alone doing only the featurization.
